//! Read-only view dispatch handlers.
//!
//! Every handler in this module returns state without mutating it. They
//! still take `&mut self` because the `DISPATCH_TABLE` requires a
//! uniform `DispatchHandler` fn-pointer type. The `&mut` is a
//! formality; no handler writes to storage.

use super::*;

impl KipioIdentityContent {
    // --------------------------------------------------------------------
    // VIEWS
    // --------------------------------------------------------------------

    #[inline(never)]
    pub(crate) fn dispatch_get_global_stats(&mut self, _args: &[u8]) -> ArbResult {
        let result = (self.global_registrations.get(), self.global_queries.get());
        Ok(result.abi_encode_params())
    }

    #[inline(never)]
    pub(crate) fn dispatch_is_paused(&mut self, _args: &[u8]) -> ArbResult {
        Ok((self.paused.get(),).abi_encode_params())
    }

    #[inline(never)]
    pub(crate) fn dispatch_get_pause_reason(&mut self, _args: &[u8]) -> ArbResult {
        Ok((self.pause_reason_hash.get(),).abi_encode_params())
    }

    #[inline(never)]
    pub(crate) fn dispatch_get_providers(&mut self, _args: &[u8]) -> ArbResult {
        let result = (
            self.storage_provider.get(),
            self.query_provider.get(),
            self.access_provider.get(),
            self.zk_verifier.get(),
        );
        Ok(result.abi_encode_params())
    }

    #[inline(never)]
    pub(crate) fn dispatch_has_access(&mut self, args: &[u8]) -> ArbResult {
        let call = hasAccessCall::abi_decode(args).map_err(|_| Vec::new())?;
        let result = self
            .vaults
            .getter(call.owner)
            .access
            .permissions
            .getter(call.content_id)
            .getter(call.grantee)
            .get();
        Ok((result,).abi_encode_params())
    }

    #[inline(never)]
    pub(crate) fn dispatch_get_commitment(&mut self, args: &[u8]) -> ArbResult {
        let call = getCommitmentCall::abi_decode(args).map_err(|_| Vec::new())?;
        let vault = self.vaults.getter(call.owner);
        let record = vault.contents.getter(call.content_id);
        let commitment = record.tx_commitment.get();
        if commitment == B256::ZERO {
            return Err(NotFound {}.abi_encode());
        }
        Ok((commitment,).abi_encode_params())
    }

    #[inline(never)]
    pub(crate) fn dispatch_get_metadata(&mut self, args: &[u8]) -> ArbResult {
        let call = getMetadataCall::abi_decode(args).map_err(|_| Vec::new())?;
        let vault = self.vaults.getter(call.owner);
        let record = vault.contents.getter(call.content_id);
        let packed = record.packed.get();
        if packed == U256::ZERO {
            return Err(NotFound {}.abi_encode());
        }
        let (version, created_at, updated_at, provider_id, is_public, storage_term, expiry_delta) =
            unpack_metadata(packed);
        let absolute_expiry = compute_absolute_expiry(created_at, expiry_delta);

        // `abi_encode_returns_tuple` accepts the raw Rust-type tuple
        // directly. It goes through `SolTypeValue<Self::ReturnTuple>`
        // instead of `SolValue`, so `u8` fields (`uint8` in Solidity)
        // are handled without requiring `u8: SolValue` — a bound that
        // Rust's coherence rules forbid us from satisfying.
        //
        // `abi_encode_returns` (without the `_tuple` suffix) is not used
        // because it expects `&Self::Return`, and `Self::Return` is the
        // named struct generated by the `sol!` macro
        // (`getMetadataReturn`), not the plain tuple.
        Ok(getMetadataCall::abi_encode_returns_tuple(&(
            version,
            created_at,
            updated_at,
            provider_id,
            is_public,
            storage_term,
            expiry_delta,
            absolute_expiry,
        )))
    }

    #[inline(never)]
    pub(crate) fn dispatch_is_public(&mut self, args: &[u8]) -> ArbResult {
        let call = isPublicCall::abi_decode(args).map_err(|_| Vec::new())?;
        let vault = self.vaults.getter(call.owner);
        let record = vault.contents.getter(call.content_id);
        let packed = record.packed.get();
        if packed == U256::ZERO {
            return Err(NotFound {}.abi_encode());
        }
        Ok((read_is_public(packed),).abi_encode_params())
    }

    #[inline(never)]
    pub(crate) fn dispatch_get_storage_info(&mut self, args: &[u8]) -> ArbResult {
        let call = getStorageInfoCall::abi_decode(args).map_err(|_| Vec::new())?;
        let vault = self.vaults.getter(call.owner);
        let record = vault.contents.getter(call.content_id);
        let packed = record.packed.get();
        if packed == U256::ZERO {
            return Err(NotFound {}.abi_encode());
        }
        let created_at = read_created_at(packed);
        let term = read_storage_term(packed);
        let delta = read_expiry_delta(packed);
        let absolute_expiry = compute_absolute_expiry(created_at, delta);

        // See `dispatch_get_metadata` for the `abi_encode_returns_tuple`
        // rationale.
        Ok(getStorageInfoCall::abi_encode_returns_tuple(&(
            term,
            delta,
            absolute_expiry,
        )))
    }

    #[inline(never)]
    pub(crate) fn dispatch_get_expiry_status(&mut self, args: &[u8]) -> ArbResult {
        let call = getExpiryStatusCall::abi_decode(args).map_err(|_| Vec::new())?;
        let vault = self.vaults.getter(call.owner);
        let record = vault.contents.getter(call.content_id);
        let packed = record.packed.get();
        if packed == U256::ZERO {
            return Err(NotFound {}.abi_encode());
        }
        let created_at = read_created_at(packed);
        let delta = read_expiry_delta(packed);
        if delta == 0 {
            return Ok((false, 0u64).abi_encode_params());
        }
        let absolute = created_at.saturating_add(delta as u64);
        let now = self.vm().block_timestamp();
        if now >= absolute {
            Ok((true, 0u64).abi_encode_params())
        } else {
            Ok((false, absolute - now).abi_encode_params())
        }
    }

    #[inline(never)]
    pub(crate) fn dispatch_get_access_policy_hash(&mut self, args: &[u8]) -> ArbResult {
        let call = getAccessPolicyHashCall::abi_decode(args).map_err(|_| Vec::new())?;
        let vault = self.vaults.getter(call.owner);
        let record = vault.contents.getter(call.content_id);
        let hash = record.access_policy_hash.get();
        if hash == B256::ZERO {
            return Err(NotFound {}.abi_encode());
        }
        Ok((hash,).abi_encode_params())
    }

    #[inline(never)]
    pub(crate) fn dispatch_get_content_list(&mut self, args: &[u8]) -> ArbResult {
        let call = getContentListCall::abi_decode(args).map_err(|_| Vec::new())?;
        let vault = self.vaults.getter(call.owner);
        let list = &vault.content_list;

        let total = list.len() as u32;
        let mut result = Vec::new();

        let start = core::cmp::min(call.offset, total);
        let end = core::cmp::min(start.saturating_add(call.limit), total);

        for i in start..end {
            if let Some(item_guard) = list.getter(i as usize) {
                result.push(item_guard.get());
            }
        }
        Ok(result.abi_encode_params())
    }

    #[inline(never)]
    pub(crate) fn dispatch_get_shared_paginated(&mut self, args: &[u8]) -> ArbResult {
        let call = getSharedPaginatedCall::abi_decode(args).map_err(|_| Vec::new())?;
        let vault = self.vaults.getter(call.owner);
        let index = vault.access.grantee_index.getter(call.content_id);

        let total = index.len() as u32;
        let mut result = Vec::new();

        let start = core::cmp::min(call.offset, total);
        let end = core::cmp::min(start.saturating_add(call.limit), total);

        for i in start..end {
            if let Some(addr_guard) = index.getter(i as usize) {
                let addr = addr_guard.get();
                if vault
                    .access
                    .permissions
                    .getter(call.content_id)
                    .getter(addr)
                    .get()
                {
                    result.push(addr);
                }
            }
        }
        Ok(result.abi_encode_params())
    }

    // --------------------------------------------------------------------
    // INTEGRITY PROOF
    // --------------------------------------------------------------------

    #[inline(never)]
    pub(crate) fn dispatch_verify_content_ownership(&mut self, args: &[u8]) -> ArbResult {
        let call = verifyContentOwnershipCall::abi_decode(args).map_err(|_| Vec::new())?;
        let vault = self.vaults.getter(call.owner);
        let record = vault.contents.getter(call.content_id);
        let stored = record.tx_commitment.get();

        if stored == B256::ZERO {
            return Err(NotFound {}.abi_encode());
        }

        // `tx_id` and `salt` are `Bytes`; `extend_from_slice` consumes a
        // `&[u8]` and `Bytes` dereferences to `[u8]` transparently.
        let mut preimage = Vec::with_capacity(call.tx_id.len() + call.salt.len());
        preimage.extend_from_slice(&call.tx_id);
        preimage.extend_from_slice(&call.salt);

        let computed = keccak(&preimage);

        Ok((computed == stored,).abi_encode_params())
    }
}
