[workspace]
members = [
  "src/kipio_core",
  "src/kipio_auth",
  "src/kipio_auth_verifier_p256",
# "src/kipio_auth_verifier_k256",
  "src/kipio_access",
  "src/kipio_registry",
  "src/kipio_recovery"
]

resolver = "3"

[workspace.dependencies]
# Enable mini-alloc to efficiently handle Vec/String in WASM
# https://github.com/OffchainLabs/stylus-sdk-rs/releases
stylus-sdk = { version = "0.10.7", features = ["mini-alloc", "hostio"] }
# https://crates.io/crates/alloy-primitives 
alloy-primitives = { version = "1.6.0", default-features = false }
# https://crates.io/crates/alloy-sol-types 
alloy-sol-types = { version = "1.6.0", default-features = false }


# Motsu 0.10.0 is the testing standard for ArbOS 52
motsu = "0.10.0"
arbitrary = { version = "1.4", features = ["derive"] }

[profile.release]
codegen-units = 1
incremental = false
lto = true
opt-level = "z" # Maximum size reduction for deployment
panic = "abort"
strip = true
