[package]
name = "kipio_stylus_harness"
version = "0.1.0"
edition = "2024"

[dependencies]
kipio_account_generated = { path = "../../../generated/rust" }
dafny_runtime = { path = "../../../generated/rust/runtime" }
stylus-sdk = { version = "0.10.9", features = ["mini-alloc", "hostio"] }
alloy-sol-types = "1.7.2"

[lib]
crate-type = ["lib", "cdylib"]

[features]
export-abi = ["stylus-sdk/export-abi"]
contract-client-gen = []
