/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.37;

interface IKipioRuntime {
    struct DispatchEnvelope {
        address field_0;
        address field_1;
        uint256 field_2;
        bytes field_3;
    }

    function dispatch(DispatchEnvelope calldata envelope) external payable returns (uint8[] memory);
    function ping() external view returns (bool);
    function getProtocolConfig() external view returns (address);
    function getModuleAddress(uint8 module_id) external view returns (address);
    function readAccountState(address account_addr) external view returns (AuthorizationStateAbi memory);
    function authorizationIsStructurallyValid(AuthorizationAbi calldata auth) external view returns (bool);
    function authorizationCanBeAcceptedFull(address account_addr, AuthorizationAbi calldata auth, IdentityAbi[] memory identities, uint256 now, bool proof_verified) external view returns (bool);
    function computeEffectiveAuthority(address account_addr, IdentityAbi[] memory identities, uint256 now) external view returns (CapabilityAbi[] memory);
    function applyPolicyConsumption(address account_addr, PolicyConsumptionAbi calldata consumption) external view returns (bool);
    function validExecutionContext(address account_addr, ExecutionContextAbi calldata context, IdentityAbi[] memory identities, bool proof_verified) external view returns (bool);
    struct CapabilityKindAbi {string name;}

    struct ScopeAtomAbi {bytes id;}

    struct ScopeAbi {ScopeAtomAbi[] atoms;}

    struct CapabilityAbi {CapabilityKindAbi kind;ScopeAbi scope;}

    struct CredentialAbi {bytes id;uint8 status;}

    struct CredentialAuthorityEntryAbi {bytes credentialId;CapabilityAbi[] authority;}

    struct RestrictionKindAbi {string name;}

    struct RestrictionAbi {RestrictionKindAbi kind;bytes value;}

    struct SessionAbi {bytes id;bytes credentialId;CapabilityAbi[] capabilities;uint256 validFrom;uint256 validUntil;RestrictionAbi[] restrictions;uint8 status;}

    struct SubjectAbi {bytes _reference;}

    struct DelegationAbi {bytes id;bytes delegatorIdentityId;SubjectAbi delegatee;CapabilityAbi[] capabilities;uint256 validFrom;uint256 validUntil;RestrictionAbi[] restrictions;bytes metadata;uint8 status;}

    struct DelegationProvenanceEntryAbi {bytes delegationId;bytes[] parents;}

    struct OptionalScopeAbi {bool hasScope;ScopeAbi scope;}

    struct RestrictionTargetAbi {CapabilityAbi capability;OptionalScopeAbi scope;}

    struct RestrictionEntryAbi {RestrictionTargetAbi target;RestrictionAbi restriction;}

    struct PolicyEffectAbi {uint8 kind;bytes id;CapabilityAbi capability;OptionalScopeAbi scope;RestrictionAbi restriction;}

    struct AuthorizationStateAbi {CapabilityAbi[] capabilities;CredentialAbi[] credentials;CredentialAuthorityEntryAbi[] credentialAuthorities;SessionAbi[] sessions;DelegationAbi[] delegations;DelegationProvenanceEntryAbi[] delegationProvenance;RestrictionEntryAbi[] restrictionMap;PolicyEffectAbi[] policyEffects;bytes[] consumedReplayKeys;}

    struct IdentityAbi {bytes id;
    SubjectAbi subject;}

    struct AuthorizationAbi {bytes credentialId;
    CapabilityAbi[] requestedAuthority;
    RestrictionAbi[] restrictions;
    uint256 validFrom;
    uint256 validUntil;
    bytes replayKey;
    bytes accountId;
    ScopeAbi scope;}

    struct PolicyAbi {PolicyEffectAbi[] effects;}

    struct PolicyConsumptionAbi {PolicyAbi policy;}

    struct ExecutionRequestAbi {AuthorizationAbi authorization;}

    struct ExecutionContextAbi {ExecutionRequestAbi request;
    AuthorizationStateAbi authorizationState;
    CapabilityAbi[] effectiveAuthority;
    uint256 evaluationTime;}
}
