/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.37;

interface IKipioEconomics {
    function updateServiceRegistry(uint8 service_id, address provider_address) external;
    function updateProtocolFee(uint256 new_fee) external;
    function updateMaxProtocolFee(uint256 new_max) external;
    function updateCreForwarder(address new_forwarder) external;
    function updateCreWorkflowId(bytes32 new_workflow_id) external;
    function updateMaxCredit(uint256 new_max) external;
    function pause() external;
    function unpause() external;
    function fundBootstrap(address beneficiary) external returns (bool, uint256);
    function createBootstrapCampaign(bytes32 campaign_id, uint256 amount_per_beneficiary, uint32 max_beneficiaries, uint64 duration_seconds) external;
    function consumeBootstrapCampaign(bytes32 campaign_id, address beneficiary) external returns (uint256);
    function closeBootstrapCampaign(bytes32 campaign_id) external returns (uint256);
    function settleEconomicObligation(address funder, uint8[] memory plan_payload) external payable returns (uint8[] memory);
    function depositForSettlement(bytes32 payment_id) external payable;
    function reclaimStaleSettlement(bytes32 payment_id) external;
    function onReport(bytes calldata metadata, bytes calldata report) external;
    function createGrant(bytes32 grant_id, uint256 amount, uint64 duration_seconds) external;
    function reclaimExpiredGrant(bytes32 grant_id) external returns (uint256);
    function setBootstrapPolicy(bool enabled, uint256 amount) external;
    function registerSponsorGovernance(bytes32 sponsor_id, address sponsor_address) external;
    function depositCredit(address user) external payable;
    function withdrawCredit(address user) external;
    function withdrawRefund(address user) external;
    function creditIdentityRefund(address identity, uint256 amount) external payable;
    function depositSponsorFunds(address user, bytes32 sponsor_id) external payable;
    function fundTreasury(address user) external payable;
    function getNonce(address account) external view returns (uint256);
    function quoteSettlement(uint256 requested_capacity, uint256 storage_quote, uint8 service_id) external view returns (uint256);
    function getOwner() external view returns (address);
    function getCreForwarder() external view returns (address);
    function getCreWorkflowId() external view returns (bytes32);
    function getProtocolFee() external view returns (uint256);
    function getMaxProtocolFee() external view returns (uint256);
    function getAvailableCredit(address account) external view returns (uint256);
    function getWithdrawableRefund(address account) external view returns (uint256);
    function getGrantRemaining(bytes32 grant_id) external view returns (uint256);
    function getGrantExpiresAt(bytes32 grant_id) external view returns (uint64);
    function getSponsorRemaining(bytes32 sponsor_id) external view returns (uint256);
    function getTreasuryReserves() external view returns (uint256);
    function getProvider(uint8 service_id) external view returns (address);
    function getPendingSettlement(bytes32 payment_id) external view returns (uint256);
    function getPendingSettlementDepositor(bytes32 payment_id) external view returns (address);
    function getPendingSettlementTimestamp(bytes32 payment_id) external view returns (uint32);
    function isPaused() external view returns (bool);
    function getMaxCredit() external view returns (uint256);
    function getBootstrapCampaign(bytes32 campaign_id) external view returns (uint256, uint32, uint32, uint64);
    function hasConsumedCampaign(bytes32 campaign_id, address beneficiary) external view returns (bool);}
