/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.37;

interface IKipioAccount {
    function getIdentityId() external view returns (address);
    function getRuntimeAddress() external view returns (address);
    function getRecoveryAddress() external view returns (address);
    function getAuthorizationState() external view returns (AuthorizationStateAbi memory);
    function isInitialized() external view returns (bool);
    function getNonce() external view returns (uint64);
    function isReplayKeyConsumed(bytes32 key) external view returns (bool);
    function isCredentialActive(bytes32 credential_id) external view returns (bool);
    function validAccount() external view returns (bool);
    function validAuthorizationState() external view returns (bool);
    function registerCredential(CredentialAbi calldata credential) external returns (bool);
    function registerSession(SessionAbi calldata session) external returns (bool);
    function registerDelegation(DelegationAbi calldata delegation, CapabilityAbi calldata delegate_capability, CapabilityAbi[] memory delegatable_authority, CapabilityAbi[] memory source_effective_authority) external returns (bool);
    function registerTransitiveDelegation(DelegationAbi calldata delegation, CapabilityAbi calldata delegate_capability, CapabilityAbi[] memory delegatable_authority, CapabilityAbi[] memory source_effective_authority, bytes[] memory parent_delegation_ids, IdentityAbi[] memory identities) external returns (bool);
    function addCapability(CapabilityAbi calldata capability) external returns (bool);
    function removeCapability(CapabilityAbi calldata capability) external returns (bool);
    function setRestriction(CapabilityAbi calldata capability, OptionalScopeAbi calldata scope, RestrictionAbi calldata restriction) external returns (bool);
    function removeRestriction(CapabilityAbi calldata capability, OptionalScopeAbi calldata scope) external returns (bool);
    function setCredentialAuthority(CredentialAbi calldata credential, CapabilityAbi[] memory authority) external returns (bool);
    function consumeReplayKey(bytes calldata replay_key) external returns (bool);
    function updateCredentialStatus(CredentialAbi calldata credential, uint8 new_status) external returns (bool);
    function updateSessionStatus(SessionAbi calldata session, uint8 new_status) external returns (bool);
    function updateDelegationStatus(DelegationAbi calldata delegation, uint8 new_status) external returns (bool);
    function executeRecovery(bytes32 request_id, RecoveryEffect[] memory effects) external;
    struct CapabilityKindAbi {string name;}

    struct ScopeAtomAbi {bytes id;}

    struct ScopeAbi {ScopeAtomAbi[] atoms;}

    struct CapabilityAbi {CapabilityKindAbi kind;ScopeAbi scope;}

    struct CredentialAbi {bytes id;uint8 status;}

    struct CredentialAuthorityEntryAbi {bytes credentialId;CapabilityAbi[] authority;}

    struct RestrictionKindAbi {string name;}

    struct RestrictionAbi {RestrictionKindAbi kind;bytes value;}

    struct SessionAbi {bytes id;bytes credentialId;CapabilityAbi[] capabilities;uint256 validFrom;uint256 validUntil;RestrictionAbi[] restrictions;uint8 status;}

    struct SubjectAbi {bytes _reference;}

    struct DelegationAbi {bytes id;bytes delegatorIdentityId;SubjectAbi delegatee;CapabilityAbi[] capabilities;uint256 validFrom;uint256 validUntil;RestrictionAbi[] restrictions;bytes metadata;uint8 status;}

    struct DelegationProvenanceEntryAbi {bytes delegationId;bytes[] parents;}

    struct OptionalScopeAbi {bool hasScope;ScopeAbi scope;}

    struct RestrictionTargetAbi {CapabilityAbi capability;OptionalScopeAbi scope;}

    struct RestrictionEntryAbi {RestrictionTargetAbi target;RestrictionAbi restriction;}

    struct PolicyEffectAbi {uint8 kind;bytes id;CapabilityAbi capability;OptionalScopeAbi scope;RestrictionAbi restriction;}

    struct AuthorizationStateAbi {CapabilityAbi[] capabilities;CredentialAbi[] credentials;CredentialAuthorityEntryAbi[] credentialAuthorities;SessionAbi[] sessions;DelegationAbi[] delegations;DelegationProvenanceEntryAbi[] delegationProvenance;RestrictionEntryAbi[] restrictionMap;PolicyEffectAbi[] policyEffects;bytes[] consumedReplayKeys;}

    struct IdentityAbi {bytes id;
    SubjectAbi subject;}

    struct RecoveryEffect {uint8 kind;
    bytes payload;}
}
