/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.37;

interface IKipioProtocolConfig {
    function transferOwnership(address new_owner) external;
    function acceptOwnership() external;
    function pause(bytes32 reason_hash) external;
    function unpause() external;
    function setRuntimeAddress(address addr) external;
    function setEconomicsAddress(address addr) external;
    function setIdentityContentAddress(address addr) external;
    function setRecoveryAddress(address addr) external;
    function setExecutionGatewayAddress(address addr) external;
    function setVerifier(uint256 curve_id, address verifier_address) external;
    function setCurveStatus(uint256 curve_id, uint256 status) external;
    function setAuthorizedLedger(address ledger, bool authorized) external;
    function getOwner() external view returns (address);
    function getPendingOwner() external view returns (address);
    function isPaused() external view returns (bool);
    function getPauseReason() external view returns (bytes32);
    function getRuntimeAddress() external view returns (address);
    function getEconomicsAddress() external view returns (address);
    function getIdentityContentAddress() external view returns (address);
    function getRecoveryAddress() external view returns (address);
    function getExecutionGatewayAddress() external view returns (address);
    function getModuleAddress(uint8 module_id) external view returns (address);
    function getVerifier(uint256 curve_id) external view returns (address);
    function getCurveStatus(uint256 curve_id) external view returns (uint256);
    function isAuthorizedLedger(address ledger) external view returns (bool);}
