/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IKipioProtocolConfig {
    function requireOwner() external view;

    function requireCore() external view returns (address);

    function initialize(address owner, address core) external;

    function getOwner() external view returns (address);

    function getPendingOwner() external view returns (address);

    function getCore() external view returns (address);

    function getVerifier(uint256 curve_id) external view returns (address);

    function getCurveStatus(uint256 curve_id) external view returns (uint256);

    function isAuthorizedLedger(address ledger) external view returns (bool);

    function transferOwnership(address new_owner) external;

    function acceptOwnership() external;

    function setVerifier(uint256 curve_id, address verifier_address) external;

    function setCurveStatus(uint256 curve_id, uint256 status) external;

    function setAuthorizedLedger(address ledger, bool authorized) external;

    function syncCoreConfig() external;

    function updateAuthModule(address new_module) external;

    function updateRegistryModule(address new_module) external;

    function updateAccessModule(address new_module) external;

    function updateTreasuryAddress(address new_treasury) external;

    function updateMinFee(uint256 new_min_fee) external;
}
