/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IKipioRegistry {
    function registerUpload(bytes32 content_id, string calldata tx_id, bool is_public) external;

    function rotateContent(bytes32 content_id, string calldata new_tx) external;

    function getActiveTx(address owner, bytes32 content_id) external view returns (string memory);

    function getVersion(address owner, bytes32 content_id) external view returns (uint64);

    function getIsPublic(address owner, bytes32 content_id) external view returns (bool);

    function getContentList(address owner, uint32 offset, uint32 limit) external view returns (bytes32[] memory);
}
