/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.37;

interface IKipioExecutionGateway {
    function execute(bytes calldata payload) external payable returns (uint8[] memory);
    function selfDeploy(bytes32 salt) external returns (address);
    function saltFor(address identity) external pure returns (bytes32);
    function predictAccount(address identity) external view returns (address);
    function protocolAddresses() external view returns (address, address, address, uint8);}
