/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IKipioAccess {
    function grantAccess(bytes32 content_id, address grantee) external;

    function revokeAccess(bytes32 content_id, address grantee) external;

    function hasAccess(address owner, bytes32 content_id, address grantee) external view returns (bool);

    function getSharedPaginated(address owner, bytes32 content_id, uint32 offset, uint32 limit) external view returns (address[] memory);
}
