/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IKipioEconomics {
    function initialize(address owner) external;

    function updateServiceRegistry(uint8 service_id, address provider_address) external;

    function fundBootstrap(address beneficiary) external returns (bool, uint256);

    function settleEconomicObligation(uint8[] memory plan_payload) external payable returns (uint8[] memory);

    function createGrant(address grant_id, uint256 amount) external;

    function setBootstrapPolicy(bool enabled, uint256 amount) external;

    function depositCredit() external payable;

    function registerSponsor(address sponsor_id) external payable;

    function fundTreasury() external payable;
}
