/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IKipioAuth {
    function initialize(address protocol_config) external;

    function register(uint8[] memory pubkey, uint256 curve) external;

    function verifyIdentityAuthorization(address user, bytes32 msg_hash, uint8[] memory signature, uint8[] memory pubkey, uint256 nonce, uint256 deadline) external returns (bool);

    function rotateKey(uint8[] memory old_pubkey, uint8[] memory new_pubkey, uint256 new_curve, uint8[] memory signature_from_old, uint256 nonce, uint256 deadline) external;

    function rotateKeyFromPolicy(address policy_ledger, bytes32 request_id, uint8[] memory new_pubkey) external;

    function verify(address _user, bytes32 digest, uint8[] memory signature, uint8[] memory pubkey, uint256 _curve) external view returns (bool);
}
