/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.37;

interface IKipioRecovery {
    function getRuntimeAddress() external view returns (address);
    function isInitialized() external view returns (bool);
    function setGuardians(address account, uint8[] memory guardian_types, bytes32[] memory guardian_identifiers, uint8[] memory guardian_curves, uint8 threshold) external;
    function updateGuardians(address account, uint8[] memory guardian_types, bytes32[] memory guardian_identifiers, uint8[] memory guardian_curves, uint8 threshold, uint8 reason) external;
    function startRecovery(address account, bytes32 target_hash, uint64 deadline) external returns (bytes32);
    function approveRecovery(address account, bytes32 request_id, bytes calldata guardian_pubkey, bytes calldata signature) external;
    function cancelRecovery(address account, bytes32 request_id, bytes calldata signer_pubkey, bytes calldata signer_signature, uint8 signer_curve) external;
    function consumeRecovery(address account, bytes32 request_id, bytes32 effects_hash) external;
    function getGuardianVersion(address account) external view returns (uint64);
    function getGuardianSet(address account, uint64 version) external view returns (uint8, uint8, uint8[] memory, bytes32[] memory, uint8[] memory);
    function getRecoveryRequest(address account, bytes32 request_id) external view returns (uint8, uint64, uint64, uint64, uint8, bytes32, bool);}
