/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IKipioCore {
    function registerUpload(bytes32 content_id, string calldata tx_id, bool is_public) external;

    function rotateContent(bytes32 content_id, string calldata new_tx) external;

    function grantAccess(bytes32 content_id, address grantee, bytes32 access_reference) external;

    function revokeAccess(bytes32 content_id, address grantee) external;

    function verify(address user, bytes32 msg_hash, uint8[] memory sig) external view returns (bool);
}
