[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["dependencies"]

optimizer = true
optimizer_runs = 200
via_ir = true

[dependencies]
forge-std = "1.15.0"

[lint]
exclude_lints = [
  "mixed-case-variable",
  "screaming-snake-case-immutable"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
